# Generated by Django 3.2.9 on 2021-11-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211122_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollGroup',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groupofusers')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll')),
            ],
        ),
    ]
