# Generated by Django 3.2.9 on 2021-11-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pollquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_answer_temp',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
