# Generated by Django 3.2.9 on 2021-11-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211126_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_answer',
        ),
    ]
