# Generated by Django 3.2.9 on 2021-11-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_date_answer_temp_answer_date_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_answer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
