export const SENT_ANSWER_FROM_USER_REQUEST = 'SENT_ANSWER_FROM_USER_REQUEST'
export const SENT_ANSWER_FROM_USER_SUCCESS = 'SENT_ANSWER_FROM_USER_SUCCESS'
export const SENT_ANSWER_FROM_USER_FAIL = 'SENT_ANSWER_FROM_USER_FAIL'

export const ANSWER_BY_POLL_ID_REQUEST = 'ANSWER_BY_POLL_ID_REQUEST'
export const ANSWER_BY_POLL_ID_SUCCESS = 'ANSWER_BY_POLL_ID_SUCCESS'
export const ANSWER_BY_POLL_ID_FAIL = 'ANSWER_BY_POLL_ID_FAIL'
export const ANSWER_BY_POLL_ID_RESET = 'ANSWER_BY_POLL_ID_RESET'

export const ANSWER_QUESTION_CREATE_POLL_REQUEST = 'ANSWER_QUESTION_CREATE_POLL_REQUEST'
export const ANSWER_QUESTION_CREATE_POLL_SUCCESS = 'ANSWER_QUESTION_CREATE_POLL_SUCCESS'
export const ANSWER_QUESTION_CREATE_POLL_FAIL = 'ANSWER_QUESTION_CREATE_POLL_FAIL'
export const ANSWER_QUESTION_CREATE_POLL_RESET = 'ANSWER_QUESTION_CREATE_POLL_RESET'

export const QUESTIONS_ANSWERS_CREATE_POLL_REQUEST = 'QUESTIONS_ANSWERS_CREATE_POLL_REQUEST'
export const QUESTIONS_ANSWERS_CREATE_POLL_SUCCESS = 'QUESTIONS_ANSWERS_CREATE_POLL_SUCCESS'
export const QUESTIONS_ANSWERS_CREATE_POLL_FAIL = 'QUESTIONS_ANSWERS_CREATE_POLL_FAIL'
export const QUESTIONS_ANSWERS_CREATE_POLL_RESET = 'QUESTIONS_ANSWERS_CREATE_POLL_RESET'
