export const POLL_LIST_REQUEST = 'POLL_LIST_REQUEST'
export const POLL_LIST_SUCCESS = 'POLL_LIST_SUCCESS'
export const POLL_LIST_FAIL = 'POLL_LIST_FAIL'
export const POLL_LIST_RESET = 'POLL_LIST_RESET'


export const POLL_REQUEST = 'POLL_REQUEST'
export const POLL_SUCCESS = 'POLL_SUCCESS'
export const POLL_FAIL = 'POLL_FAIL'
export const POLL_RESET = 'POLL_RESET'

export const POLL_DELETE_REQUEST = 'POLL_DELETE_REQUEST'
export const POLL_DELETE_SUCCESS = 'POLL_DELETE_SUCCESS'
export const POLL_DELETE_FAIL = 'POLL_DELETE_FAIL'

export const POLL_DESCRIPTION_CREATE_POLL_REQUEST = 'POLL_DESCRIPTION_CREATE_POLL_REQUEST'
export const POLL_DESCRIPTION_CREATE_POLL_SUCCESS = 'POLL_DESCRIPTION_CREATE_POLL_SUCCESS'
export const POLL_DESCRIPTION_CREATE_POLL_FAIL = 'POLL_DESCRIPTION_CREATE_POLL_FAIL'
export const POLL_DESCRIPTION_CREATE_POLL_RESET = 'POLL_DESCRIPTION_CREATE_POLL_RESET'

export const SENT_CREATED_POLL_REQUEST = 'SENT_CREATED_POLL_REQUEST'
export const SENT_CREATED_POLL_SUCCESS = 'SENT_CREATED_POLL_SUCCESS'
export const SENT_CREATED_POLL_FAIL = 'SENT_CREATED_POLL_FAIL'
export const SENT_CREATED_POLL_RESET = 'SENT_CREATED_POLL_RESET'

export const DOWNLOAD_REPORT_POLL_REQUEST = 'DOWNLOAD_REPORT_POLL_REQUEST'
export const DOWNLOAD_REPORT_POLL_SUCCESS = 'DOWNLOAD_REPORT_POLL_SUCCESS'
export const DOWNLOAD_REPORT_POLL_FAIL = 'DOWNLOAD_REPORT_POLL_FAIL'
export const DOWNLOAD_REPORT_POLL_RESET = 'DOWNLOAD_REPORT_POLL_RESET'


