export const USER_POLL_LIST_REQUEST = 'USER_POLL_LIST_REQUEST'
export const USER_POLL_LIST_SUCCESS = 'USER_POLL_LIST_SUCCESS'
export const USER_POLL_LIST_FAIL = 'USER_POLL_LIST_FAIL'
export const USER_POLL_LIST_RESET = 'USER_POLL_LIST_RESET'