export const USER_GROUP_LIST_REQUEST = 'USER_GROUP_LIST_REQUEST'
export const USER_GROUP_LIST_SUCCESS = 'USER_GROUP_LIST_SUCCESS'
export const USER_GROUP_LIST_FAIL = 'USER_GROUP_LIST_FAIL'
export const USER_GROUP_LIST_RESET = 'USER_GROUP_LIST_RESET'